package com.example.allAuth.enums;

public enum FileNameType {
    Tin_Certificate,
    Salary_Slip,
    Bank_Statement,
    Investment_Slip,
    Bond_Or_Debenture_Slip,
    Nbr_Slip,
    Bank_Statement_for_Interest,
    Loan_Statement_for_purchase_Bond,
    House_Property_Rent_Agreement,
    House_ProperTy_Rent_Receipt,
    House_ProperTy_Rent_Receipt_Statement,
    Your_Photo,
    House_Property_Bank_Statement,
    House_Property_Insurance_Statement,
    Business_or_Profession_income_statement,
    Business_or_Profession_income_Balance_Sheet,
    Partnership_Or_Firm_Income_Statement,
    Partnership_Or_Firm_Balance_Sheet,
    Agreement_of_Sale_OrTransfer_of_Ownership,
    Chalan_or_payOrder_copy_of_TDS,
    Statement_of_Profit_from_TDS,
    Statement_Of_profit_from_Share_Transfer,
    Bank_statement_for_Interest_for_deposit,
    Dividend_Certificate_or_Bank_Statement,
    TDS_Chalan_Or_PO_OR_BankDraft_Or_AccountPayeeCheckCopy,
    Anything_Other,
    Your_Signature
}
